version: '3.8'
services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
#    volumes:
#      - ./db/create_db_001.sql:/docker-entrypoint-initdb.d/create_db_001.sql

